Breed.create(dogs:"Unknown")
Breed.create(dogs:"Affenpinscher")
Breed.create(dogs:"Afghan Hound")
Breed.create(dogs:"Airedale Terrier")
Breed.create(dogs:"Akita Inu")
Breed.create(dogs:"Alaskan Malamute")
Breed.create(dogs:"American Akita")
Breed.create(dogs:"American Staffordshire Terrier")
Breed.create(dogs:"Anatolian Shepherd Dog")
Breed.create(dogs:"Appenzeller Cattle Dog")
Breed.create(dogs:"Artesian Norman Basset")
Breed.create(dogs:"Australian Cattle Dog")
Breed.create(dogs:"Australian Kelpie")
Breed.create(dogs:"Australian Shepherd Dog")
Breed.create(dogs:"Australian Silky Terrier")
Breed.create(dogs:"Australian Terrier")
Breed.create(dogs:"Azawakh")
Breed.create(dogs:"Barbet")
Breed.create(dogs:"Basenji")
Breed.create(dogs:"Basset Artesien Normand")
Breed.create(dogs:"Basset Bleu de Gascogne")
Breed.create(dogs:"Basset Fauve de Bretagne")
Breed.create(dogs:"Basset Hound")
Breed.create(dogs:"Bavarian Mountain Scenthound")
Breed.create(dogs:"Beagle")
Breed.create(dogs:"Beauceron")
Breed.create(dogs:"Bedlington Terrier")
Breed.create(dogs:"Belgian Shepherd Dog Groenendael")
Breed.create(dogs:"Belgian Shepherd Lakenois")
Breed.create(dogs:"Belgian Shepherd Malinois")
Breed.create(dogs:"Belgian Shepherd Tervuren")
Breed.create(dogs:"Bergamasco")
Breed.create(dogs:"Berger Picard")
Breed.create(dogs:"Bernese Mountain Dog")
Breed.create(dogs:"Bichon Frise")
Breed.create(dogs:"Black and Tan Coonhound")
Breed.create(dogs:"Black Russian Terrier")
Breed.create(dogs:"Bloodhound")
Breed.create(dogs:"Bolognese")
Breed.create(dogs:"Border Terrier")
Breed.create(dogs:"Borzoi")
Breed.create(dogs:"Boston Terrier")
Breed.create(dogs:"Bouvier des Flandres")
Breed.create(dogs:"Boxer")
Breed.create(dogs:"Bracco Italiano")
Breed.create(dogs:"Briard")
Breed.create(dogs:"Briquet Griffon Vendeen")
Breed.create(dogs:"Bull Terrier")
Breed.create(dogs:"Bull Terrier Miniature")
Breed.create(dogs:"Bulldog")
Breed.create(dogs:"Bullmastiff")
Breed.create(dogs:"Cairn Terrier")
Breed.create(dogs:"Canaan Dog")
Breed.create(dogs:"Canadian Eskimo Dog")
Breed.create(dogs:"Catalonian Sheepdog Long Haired")
Breed.create(dogs:"Catalonian Sheepdog Smooth Haired")
Breed.create(dogs:"Caucasian Shepherd Dog")
Breed.create(dogs:"Cavalier King Charles Spaniel")
Breed.create(dogs:"Central Asia Shepherd Dog")
Breed.create(dogs:"Cesky Terrier")
Breed.create(dogs:"Chihuahua Long Coat")
Breed.create(dogs:"Chihuahua Smooth Coat")
Breed.create(dogs:"Chinese Crested")
Breed.create(dogs:"Chow Chow")
Breed.create(dogs:"Cirneco Dell Etna")
Breed.create(dogs:"Collie Bearded")
Breed.create(dogs:"Collie Border")
Breed.create(dogs:"Collie Rough")
Breed.create(dogs:"Collie Smooth")
Breed.create(dogs:"Coton de Tulear")
Breed.create(dogs:"Czekoslovakian Wolfdog")
Breed.create(dogs:"Dachshund Long Haired")
Breed.create(dogs:"Dachshund Long Haired Kaninchen")
Breed.create(dogs:"Dachshund Long Haired Miniature")
Breed.create(dogs:"Dachshund Smooth Haired")
Breed.create(dogs:"Dachshund Smooth Haired Kaninchen")
Breed.create(dogs:"Dachshund Smooth Haired Miniature")
Breed.create(dogs:"Dachshund Wire Haired")
Breed.create(dogs:"Dachshund Wire Haired Kaninchen")
Breed.create(dogs:"Dachshund Wire Haired Miniature")
Breed.create(dogs:"Dalmatian")
Breed.create(dogs:"Dandie Dinmont Terrier")
Breed.create(dogs:"Deerhound")
Breed.create(dogs:"Doberman Pinscher")
Breed.create(dogs:"Dogo Argentino")
Breed.create(dogs:"Dogo Canario")
Breed.create(dogs:"Dogue de Bordeaux")
Breed.create(dogs:"Dutch Schapendoes")
Breed.create(dogs:"Dutch Shepherd Long Haired")
Breed.create(dogs:"Dutch Shepherd Short Haired")
Breed.create(dogs:"English Toy Terrier")
Breed.create(dogs:"Estrela Mountain Dog")
Breed.create(dogs:"Estrela Mountain Dog Long Haired")
Breed.create(dogs:"Estrela Mountain Dog Smooth Haired")
Breed.create(dogs:"Eurasier")
Breed.create(dogs:"Finnish Lapphund")
Breed.create(dogs:"Finnish Spitz")
Breed.create(dogs:"Fox Terrier Smooth Haired")
Breed.create(dogs:"Fox Terrier Wire Haired")
Breed.create(dogs:"Foxhound")
Breed.create(dogs:"French Bulldog")
Breed.create(dogs:"Frisian Pointing Dog")
Breed.create(dogs:"Galgo Espanol")
Breed.create(dogs:"German Long Haired Pointer")
Breed.create(dogs:"German Pinscher")
Breed.create(dogs:"German Shepherd Dog")
Breed.create(dogs:"German Shepherd Dog (Long Coat)")
Breed.create(dogs:"German Shorthaired Pointer")
Breed.create(dogs:"German Spitz Gross")
Breed.create(dogs:"German Spitz Klein")
Breed.create(dogs:"German Spitz Mittel")
Breed.create(dogs:"German Wirehaired Pointer")
Breed.create(dogs:"Giant Schnauzer")
Breed.create(dogs:"Grand Basset Griffon Vendeen")
Breed.create(dogs:"Grand Bleu de Gascogne")
Breed.create(dogs:"Grand Griffon Vendeen")
Breed.create(dogs:"Great Dane")
Breed.create(dogs:"Great Swiss Mountain Dog")
Breed.create(dogs:"Greyhound")
Breed.create(dogs:"Greyhound (Retired Racing)")
Breed.create(dogs:"Griffon Belge")
Breed.create(dogs:"Griffon Bruxellois")
Breed.create(dogs:"Griffon Fauve de Bretagne")
Breed.create(dogs:"Griffon Korthals")
Breed.create(dogs:"Halden Hound")
Breed.create(dogs:"Hamiltonstovare")
Breed.create(dogs:"Hanoverian Scenthound")
Breed.create(dogs:"Harrier")
Breed.create(dogs:"Havanese")
Breed.create(dogs:"Hovawart")
Breed.create(dogs:"Hungarian Kuvasz")
Breed.create(dogs:"Hungarian Puli")
Breed.create(dogs:"Hungarian Pumi")
Breed.create(dogs:"Hungarian Vizsla")
Breed.create(dogs:"Hungarian Wire Haired Vizsla")
Breed.create(dogs:"Ibizan Hound")
Breed.create(dogs:"Irish Glen of Imaal Terrier")
Breed.create(dogs:"Irish Soft Coated Wheaten Terrier")
Breed.create(dogs:"Irish Terrier")
Breed.create(dogs:"Irish Wolfhound")
Breed.create(dogs:"Italian Corso Dog")
Breed.create(dogs:"Italian Greyhound")
Breed.create(dogs:"Italian Spinone")
Breed.create(dogs:"Italian Volpino")
Breed.create(dogs:"Jack Russell Terrier")
Breed.create(dogs:"Japanese Akita")
Breed.create(dogs:"Japanese Chin")
Breed.create(dogs:"Japanese Shiba Inu")
Breed.create(dogs:"Japanese Spitz")
Breed.create(dogs:"Karelian Bear Dog")
Breed.create(dogs:"Keeshond")
Breed.create(dogs:"Kerry Beagle")
Breed.create(dogs:"Kerry Blue Terrier")
Breed.create(dogs:"King Charles Spaniel")
Breed.create(dogs:"Komondor")
Breed.create(dogs:"Kooikerhondje")
Breed.create(dogs:"Lagotto Romagnolo")
Breed.create(dogs:"Lakeland Terrier")
Breed.create(dogs:"Lancashire Heeler")
Breed.create(dogs:"Landseer")
Breed.create(dogs:"Lapinporokoira")
Breed.create(dogs:"Large Munsterlander")
Breed.create(dogs:"Leonberger")
Breed.create(dogs:"Lhasa Apso")
Breed.create(dogs:"Löwchen")
Breed.create(dogs:"Magyar Agar")
Breed.create(dogs:"Mallorca Mastiff")
Breed.create(dogs:"Maltese")
Breed.create(dogs:"Manchester Terrier")
Breed.create(dogs:"Maremma Sheepdog")
Breed.create(dogs:"Mastiff")
Breed.create(dogs:"Mexican Hairless Dog Intermediate")
Breed.create(dogs:"Mexican Hairless Dog Miniature")
Breed.create(dogs:"Mexican Hairless Dog Standard")
Breed.create(dogs:"Mudi")
Breed.create(dogs:"Neapolitan Mastiff")
Breed.create(dogs:"Newfoundland")
Breed.create(dogs:"Norfolk Terrier")
Breed.create(dogs:"Norrbottenspitz")
Breed.create(dogs:"Norwegian Buhund")
Breed.create(dogs:"Norwegian Elkhound")
Breed.create(dogs:"Norwich Terrier")
Breed.create(dogs:"Nova Scotia Duck Tolling Retriever")
Breed.create(dogs:"Old English Sheepdog")
Breed.create(dogs:"Otterhound")
Breed.create(dogs:"Papillon")
Breed.create(dogs:"Parson Russell Terrier")
Breed.create(dogs:"Pekingese")
Breed.create(dogs:"Peruvian Hairless Dog Large")
Breed.create(dogs:"Peruvian Hairless Dog Medium")
Breed.create(dogs:"Peruvian Hairless Dog Miniature")
Breed.create(dogs:"Petit Basset Griffon Vendéen")
Breed.create(dogs:"Petit Brabançon")
Breed.create(dogs:"Phalene")
Breed.create(dogs:"Pharaoh Hound")
Breed.create(dogs:"Picardy Spaniel")
Breed.create(dogs:"Pinscher")
Breed.create(dogs:"Pinscher Miniature")
Breed.create(dogs:"Pointer")
Breed.create(dogs:"Polish Lowland Sheepdog")
Breed.create(dogs:"Pomeranian")
Breed.create(dogs:"Poodle Medium")
Breed.create(dogs:"Poodle Miniature")
Breed.create(dogs:"Poodle Standard")
Breed.create(dogs:"Poodle Toy")
Breed.create(dogs:"Portuguese Podengo")
Breed.create(dogs:"Portuguese Podengo Smooth Coat Large")
Breed.create(dogs:"Portuguese Podengo Smooth Coat Medium")
Breed.create(dogs:"Portuguese Podengo Smooth Coat Miniature")
Breed.create(dogs:"Portuguese Podengo Wire Coat Large")
Breed.create(dogs:"Portuguese Podengo Wire Coat Medium")
Breed.create(dogs:"Portuguese Podengo Wire Coat Miniature")
Breed.create(dogs:"Portuguese Pointing Dog")
Breed.create(dogs:"Portuguese Water Dog")
Breed.create(dogs:"Pug")
Breed.create(dogs:"Pumi")
Breed.create(dogs:"Pyrenean Mastiff")
Breed.create(dogs:"Pyrenean Mountain Dog")
Breed.create(dogs:"Pyrenean Sheepdog")
Breed.create(dogs:"Pyrenean Sheepdog Long Haired")
Breed.create(dogs:"Pyrenean Sheepdog Smooth Faced")
Breed.create(dogs:"Retriever Chesapeake Bay")
Breed.create(dogs:"Retriever Curly Coated")
Breed.create(dogs:"Retriever Flat Coated")
Breed.create(dogs:"Retriever Golden")
Breed.create(dogs:"Retriever Labrador")
Breed.create(dogs:"Rhodesian Ridgeback")
Breed.create(dogs:"Romanian Mioritic")
Breed.create(dogs:"Rottweiler")
Breed.create(dogs:"Russkiy Toy Long Haired")
Breed.create(dogs:"Russkiy Toy Smooth Haired")
Breed.create(dogs:"Saluki")
Breed.create(dogs:"Samoyed")
Breed.create(dogs:"Schapendoes")
Breed.create(dogs:"Schipperke")
Breed.create(dogs:"Schnauzer Miniature")
Breed.create(dogs:"Schnauzer Standard")
Breed.create(dogs:"Scottish Terrier")
Breed.create(dogs:"Sealyham Terrier")
Breed.create(dogs:"Segugio Italiano")
Breed.create(dogs:"Setter English")
Breed.create(dogs:"Setter Gordon")
Breed.create(dogs:"Setter Irish")
Breed.create(dogs:"Setter Irish Red and White")
Breed.create(dogs:"Shar Pei")
Breed.create(dogs:"Shetland Sheepdog")
Breed.create(dogs:"Shih Tzu")
Breed.create(dogs:"Siberian Husky")
Breed.create(dogs:"Skye Terrier")
Breed.create(dogs:"Sloughi")
Breed.create(dogs:"Slovakian Wire-haired Pointing Dog")
Breed.create(dogs:"Small Munsterlander")
Breed.create(dogs:"Spaniel American Cocker")
Breed.create(dogs:"Spaniel Brittany")
Breed.create(dogs:"Spaniel Clumber")
Breed.create(dogs:"Spaniel Cocker")
Breed.create(dogs:"Spaniel English Springer")
Breed.create(dogs:"Spaniel Field")
Breed.create(dogs:"Spaniel Irish Water")
Breed.create(dogs:"Spaniel Sussex")
Breed.create(dogs:"Spaniel Welsh Springer")
Breed.create(dogs:"Spanish Greyhound")
Breed.create(dogs:"Spanish Mastiff")
Breed.create(dogs:"Spanish Water Dog")
Breed.create(dogs:"St Bernard (Long Haired)")
Breed.create(dogs:"St Bernard (Short Haired)")
Breed.create(dogs:"St. Bernard")
Breed.create(dogs:"Staffordshire Bull Terrier")
Breed.create(dogs:"Swedish Lapphund")
Breed.create(dogs:"Swedish Vallhund")
Breed.create(dogs:"Tatra Shepherd Dog")
Breed.create(dogs:"Thai Ridgeback Dog")
Breed.create(dogs:"Tibetan Mastiff")
Breed.create(dogs:"Tibetan Spaniel")
Breed.create(dogs:"Tibetan Terrier")
Breed.create(dogs:"Treeing Walker Coonhound")
Breed.create(dogs:"Weimaraner Long Haired")
Breed.create(dogs:"Weimaraner Short Haired")
Breed.create(dogs:"Welsh Corgi Cardigan")
Breed.create(dogs:"Welsh Corgi Pembroke")
Breed.create(dogs:"Welsh Terrier")
Breed.create(dogs:"West Highland White Terrier")
Breed.create(dogs:"Whippet")
Breed.create(dogs:"White Swiss Shepherd Dog")
Breed.create(dogs:"Wire-Haired Pointing Griffon Korthals")
Breed.create(dogs:"Yorkshire Terrier")
Breed.create(dogs:"Yugoslavian Shepherd Dog – Sharplanina")
Breed.create(cats:"Unknown")
Breed.create(cats:"Abyssinian")
Breed.create(cats:"Aegean cat")
Breed.create(cats:"Australian Mist")
Breed.create(cats:"American Polydactyl")
Breed.create(cats:"American Bobtail")
Breed.create(cats:"American Curl")
Breed.create(cats:"American Longhair")
Breed.create(cats:"American Shorthair")
Breed.create(cats:"American Wirehair")
Breed.create(cats:"Asian Semi-longhair")
Breed.create(cats:"Balinese")
Breed.create(cats:"Bengal")
Breed.create(cats:"Birman")
Breed.create(cats:"Bombay")
Breed.create(cats:"Brazilian Shorthair")
Breed.create(cats:"British Shorthair")
Breed.create(cats:"British Longhair")
Breed.create(cats:"Burmese")
Breed.create(cats:"Burmilla")
Breed.create(cats:"California Spangled Cat")
Breed.create(cats:"Chantilly/Tiffany")
Breed.create(cats:"Chartreux")
Breed.create(cats:"Chausie")
Breed.create(cats:"Cheetoh")
Breed.create(cats:"Colorpoint Shorthair")
Breed.create(cats:"Cornish Rex")
Breed.create(cats:"Cymric")
Breed.create(cats:"Devon Rex")
Breed.create(cats:"Donskoy or Don Sphynx")
Breed.create(cats:"Dragon Li")
Breed.create(cats:"Egyptian Mau")
Breed.create(cats:"European Shorthair")
Breed.create(cats:"Exotic Shorthair")
Breed.create(cats:"German Rex")
Breed.create(cats:"Havana Brown")
Breed.create(cats:"Himalayan/Colorpoint Persian")
Breed.create(cats:"Japanese Bobtail")
Breed.create(cats:"Javanese")
Breed.create(cats:"Korat")
Breed.create(cats:"Kurilian Bobtail")
Breed.create(cats:"LaPerm")
Breed.create(cats:"Maine Coon")
Breed.create(cats:"Manx")
Breed.create(cats:"Munchkin")
Breed.create(cats:"Nebelung")
Breed.create(cats:"Norwegian Forest Cat")
Breed.create(cats:"Ocicat")
Breed.create(cats:"Ojos Azules")
Breed.create(cats:"Oregon Rex")
Breed.create(cats:"Oriental Bicolour")
Breed.create(cats:"Oriental Shorthair")
Breed.create(cats:"Oriental Longhair")
Breed.create(cats:"Persian")
Breed.create(cats:"Peterbald")
Breed.create(cats:"Pixie-bob")
Breed.create(cats:"Ragamuffin")
Breed.create(cats:"Ragdoll")
Breed.create(cats:"Russian Blue")
Breed.create(cats:"Russian White, Black and Tabby")
Breed.create(cats:"Savannah")
Breed.create(cats:"Scottish Fold")
Breed.create(cats:"Selkirk Rex")
Breed.create(cats:"Serengeti cat")
Breed.create(cats:"Siamese")
Breed.create(cats:"Siberian")
Breed.create(cats:"Singapura")
Breed.create(cats:"Snowshoe")
Breed.create(cats:"Sokoke")
Breed.create(cats:"Somali")
Breed.create(cats:"Sphynx")
Breed.create(cats:"Sumxu")
Breed.create(cats:"Thai/Old-style Siamese")
Breed.create(cats:"Tonkinese")
Breed.create(cats:"Toyger")
Breed.create(cats:"Turkish Angora")
Breed.create(cats:"Turkish Van")
Breed.create(cats:"Turkish Vankedisi")
Breed.create(cats:"Twisty Cat/Squitten")
Breed.create(cats:"Ukrainian Levkoy")
Breed.create(cats:"Ussuri")
Breed.create(cats:"York Chocolate Cat")